# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Ward < Formula
  desc "Local-first MCP firewall, debugger, and replay layer"
  homepage "https://github.com/oliver-morrow/ward"
  version "0.1.0"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/oliver-morrow/ward/releases/download/v0.1.0/ward_0.1.0_darwin_amd64.tar.gz"
      sha256 "fcb212439262b87e1bc73f0790401bd366847fff58e291802a2d0ce286711710"

      define_method(:install) do
        bin.install "ward"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/oliver-morrow/ward/releases/download/v0.1.0/ward_0.1.0_darwin_arm64.tar.gz"
      sha256 "62fb7b6d6f8a0887f070fd051d1f43f7ced5b776a6f584bfb4a97b6e0a0c0830"

      define_method(:install) do
        bin.install "ward"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/oliver-morrow/ward/releases/download/v0.1.0/ward_0.1.0_linux_amd64.tar.gz"
      sha256 "2ea59ec8e74b9251792c06e8e03c687e8a2eeb0900affe881a5f24df3985d16f"
      define_method(:install) do
        bin.install "ward"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/oliver-morrow/ward/releases/download/v0.1.0/ward_0.1.0_linux_arm64.tar.gz"
      sha256 "ed77b09efa41d8ec01b52ecc387633b1914ffbf66cc8aa9a2421fa9c9f24ce17"
      define_method(:install) do
        bin.install "ward"
      end
    end
  end

  test do
    system "#{bin}/ward", "--help"
  end
end
