# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Ward < Formula
  desc "Local-first MCP firewall, debugger, and replay layer"
  homepage "https://github.com/oliver-morrow/ward"
  version "0.1.1"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/oliver-morrow/ward/releases/download/v0.1.1/ward_0.1.1_darwin_amd64.tar.gz"
      sha256 "7829118fee36820c21164fb05b17c72be3ab39808f5abb2d0c6e5698cb1e309b"

      define_method(:install) do
        bin.install "ward"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/oliver-morrow/ward/releases/download/v0.1.1/ward_0.1.1_darwin_arm64.tar.gz"
      sha256 "e5cb16740aaede2045be0e4e8fe6e625956702f7b3ac1725df6029df50386a93"

      define_method(:install) do
        bin.install "ward"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/oliver-morrow/ward/releases/download/v0.1.1/ward_0.1.1_linux_amd64.tar.gz"
      sha256 "32def008aa0f1adac2e659f6067aa943dc9e0621a8708a27496a3bebce03f610"
      define_method(:install) do
        bin.install "ward"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/oliver-morrow/ward/releases/download/v0.1.1/ward_0.1.1_linux_arm64.tar.gz"
      sha256 "18086481aa7a3d63ad9561e1816c5657b1777cbf22dd5056f26e6ea2735e0bb3"
      define_method(:install) do
        bin.install "ward"
      end
    end
  end

  test do
    system "#{bin}/ward", "--help"
  end
end
